---
- hosts: spacewalk-server
  sudo: yes
  pre_tasks:
    - hostname: name=spacewalk-test
  roles:
    - spacewalk
    - role: iptables
      firewall_allowed_tcp_ports:
      - 22
      - 80
      - 443
      - 5222
      - 5269
    - role: spacewalk-customisations
    - role: spacewalk-client
